version: '3.9'
services:
  api-gateway:
    build:
      context: ../ApiGateway
    ports:
      - "5000:80"
    depends_on:
      - service-a
      - service-b

  service-a:
    build:
      context: ../Services/ServiceA
    ports:
      - "5001:80"

  service-b:
    build:
      context: ../Services/ServiceB
    ports:
      - "5002:80"